classdef MissionStatus < robotics.ros.Message
    %MissionStatus MATLAB implementation of nautonomous_mission_msgs/MissionStatus
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_mission_msgs/MissionStatus' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '386f73e3a4113bf532e57daaccc43862' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Progression
        Status
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Progression', 'Status'} % List of non-constant message properties
        ROSPropertyList = {'progression', 'status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionStatus(msg)
            %MissionStatus Construct the message object MissionStatus
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function progression = get.Progression(obj)
            %get.Progression Get the value for property Progression
            progression = int32(obj.JavaMessage.getProgression);
        end
        
        function set.Progression(obj, progression)
            %set.Progression Set the value for property Progression
            validateattributes(progression, {'numeric'}, {'nonempty', 'scalar'}, 'MissionStatus', 'Progression');
            
            obj.JavaMessage.setProgression(progression);
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            status = char(obj.JavaMessage.getStatus);
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            validateattributes(status, {'char'}, {}, 'MissionStatus', 'Status');
            
            obj.JavaMessage.setStatus(status);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Progression = obj.Progression;
            cpObj.Status = obj.Status;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Progression = strObj.Progression;
            obj.Status = strObj.Status;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Progression = obj.Progression;
            strObj.Status = obj.Status;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_mission_msgs.MissionStatus.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_mission_msgs.MissionStatus;
            obj.reload(strObj);
        end
    end
end
