classdef OperationPlan < robotics.ros.Message
    %OperationPlan MATLAB implementation of nautonomous_mission_msgs/OperationPlan
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_mission_msgs/OperationPlan' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f2383aa623dc25a09de1c01d4e5fc78e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPose2DClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Pose2D') % Dispatch to MATLAB class for message type geometry_msgs/Pose2D
    end
    
    properties (Dependent)
        Uuid
        Name
        AutomaticRouting
        Route
        Actions
    end
    
    properties (Access = protected)
        Cache = struct('Route', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Actions', 'AutomaticRouting', 'Name', 'Route', 'Uuid'} % List of non-constant message properties
        ROSPropertyList = {'actions', 'automatic_routing', 'name', 'route', 'uuid'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = OperationPlan(msg)
            %OperationPlan Construct the message object OperationPlan
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function uuid = get.Uuid(obj)
            %get.Uuid Get the value for property Uuid
            uuid = int32(obj.JavaMessage.getUuid);
        end
        
        function set.Uuid(obj, uuid)
            %set.Uuid Set the value for property Uuid
            validateattributes(uuid, {'numeric'}, {'nonempty', 'scalar'}, 'OperationPlan', 'Uuid');
            
            obj.JavaMessage.setUuid(uuid);
        end
        
        function name = get.Name(obj)
            %get.Name Get the value for property Name
            name = char(obj.JavaMessage.getName);
        end
        
        function set.Name(obj, name)
            %set.Name Set the value for property Name
            validateattributes(name, {'char'}, {}, 'OperationPlan', 'Name');
            
            obj.JavaMessage.setName(name);
        end
        
        function automaticrouting = get.AutomaticRouting(obj)
            %get.AutomaticRouting Get the value for property AutomaticRouting
            automaticrouting = logical(obj.JavaMessage.getAutomaticRouting);
        end
        
        function set.AutomaticRouting(obj, automaticrouting)
            %set.AutomaticRouting Set the value for property AutomaticRouting
            validateattributes(automaticrouting, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'OperationPlan', 'AutomaticRouting');
            
            obj.JavaMessage.setAutomaticRouting(automaticrouting);
        end
        
        function route = get.Route(obj)
            %get.Route Get the value for property Route
            if isempty(obj.Cache.Route)
                javaArray = obj.JavaMessage.getRoute;
                array = obj.readJavaArray(javaArray, obj.GeometryMsgsPose2DClass);
                obj.Cache.Route = feval(obj.GeometryMsgsPose2DClass, array);
            end
            route = obj.Cache.Route;
        end
        
        function set.Route(obj, route)
            %set.Route Set the value for property Route
            if ~isvector(route) && isempty(route)
                % Allow empty [] input
                route = feval([obj.GeometryMsgsPose2DClass '.empty'], 0, 1);
            end
            
            validateattributes(route, {obj.GeometryMsgsPose2DClass}, {'vector'}, 'OperationPlan', 'Route');
            
            javaArray = obj.JavaMessage.getRoute;
            array = obj.writeJavaArray(route, javaArray, obj.GeometryMsgsPose2DClass);
            obj.JavaMessage.setRoute(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Route)
                obj.Cache.Route = [];
                obj.Cache.Route = obj.Route;
            end
        end
        
        function actions = get.Actions(obj)
            %get.Actions Get the value for property Actions
            javaArray = obj.JavaMessage.getActions;
            array = obj.readJavaArray(javaArray, 'char');
            actions = arrayfun(@(x) char(x), array, 'UniformOutput', false);
        end
        
        function set.Actions(obj, actions)
            %set.Actions Set the value for property Actions
            if ~isvector(actions) && isempty(actions)
                % Allow empty [] input
                actions = cell.empty(0,1);
            end
            
            validateattributes(actions, {'cell'}, {'vector'}, 'OperationPlan', 'Actions');
            if any(cellfun(@(x) ~ischar(x), actions))
                error(message('robotics:ros:message:CellArrayStringError', ...
                    'actions'));
            end
            
            javaArray = obj.JavaMessage.getActions;
            array = obj.writeJavaArray(actions, javaArray, 'char');
            obj.JavaMessage.setActions(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Route = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Uuid = obj.Uuid;
            cpObj.Name = obj.Name;
            cpObj.AutomaticRouting = obj.AutomaticRouting;
            cpObj.Actions = obj.Actions;
            
            % Recursively copy compound properties
            cpObj.Route = copy(obj.Route);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Uuid = strObj.Uuid;
            obj.Name = strObj.Name;
            obj.AutomaticRouting = strObj.AutomaticRouting;
            obj.Actions = strObj.Actions;
            RouteCell = arrayfun(@(x) feval([obj.GeometryMsgsPose2DClass '.loadobj'], x), strObj.Route, 'UniformOutput', false);
            obj.Route = vertcat(RouteCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Uuid = obj.Uuid;
            strObj.Name = obj.Name;
            strObj.AutomaticRouting = obj.AutomaticRouting;
            strObj.Actions = obj.Actions;
            strObj.Route = arrayfun(@(x) saveobj(x), obj.Route);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_mission_msgs.OperationPlan.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_mission_msgs.OperationPlan;
            obj.reload(strObj);
        end
    end
end
