classdef Obstacles < robotics.ros.Message
    %Obstacles MATLAB implementation of nautonomous_mpc_msgs/Obstacles
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_mpc_msgs/Obstacles' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'fe7999e0444c9ee0a588cc9f67871716' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        NautonomousMpcMsgsObstacleClass = robotics.ros.msg.internal.MessageFactory.getClassForType('nautonomous_mpc_msgs/Obstacle') % Dispatch to MATLAB class for message type nautonomous_mpc_msgs/Obstacle
    end
    
    properties (Dependent)
        Obstacles_
    end
    
    properties (Access = protected)
        Cache = struct('Obstacles_', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Obstacles_'} % List of non-constant message properties
        ROSPropertyList = {'obstacles'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Obstacles(msg)
            %Obstacles Construct the message object Obstacles
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function obstacles_ = get.Obstacles_(obj)
            %get.Obstacles_ Get the value for property Obstacles_
            if isempty(obj.Cache.Obstacles_)
                javaArray = obj.JavaMessage.getObstacles;
                array = obj.readJavaArray(javaArray, obj.NautonomousMpcMsgsObstacleClass);
                obj.Cache.Obstacles_ = feval(obj.NautonomousMpcMsgsObstacleClass, array);
            end
            obstacles_ = obj.Cache.Obstacles_;
        end
        
        function set.Obstacles_(obj, obstacles_)
            %set.Obstacles_ Set the value for property Obstacles_
            if ~isvector(obstacles_) && isempty(obstacles_)
                % Allow empty [] input
                obstacles_ = feval([obj.NautonomousMpcMsgsObstacleClass '.empty'], 0, 1);
            end
            
            validateattributes(obstacles_, {obj.NautonomousMpcMsgsObstacleClass}, {'vector'}, 'Obstacles', 'Obstacles_');
            
            javaArray = obj.JavaMessage.getObstacles;
            array = obj.writeJavaArray(obstacles_, javaArray, obj.NautonomousMpcMsgsObstacleClass);
            obj.JavaMessage.setObstacles(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Obstacles_)
                obj.Cache.Obstacles_ = [];
                obj.Cache.Obstacles_ = obj.Obstacles_;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Obstacles_ = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Obstacles_ = copy(obj.Obstacles_);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            Obstacles_Cell = arrayfun(@(x) feval([obj.NautonomousMpcMsgsObstacleClass '.loadobj'], x), strObj.Obstacles_, 'UniformOutput', false);
            obj.Obstacles_ = vertcat(Obstacles_Cell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Obstacles_ = arrayfun(@(x) saveobj(x), obj.Obstacles_);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_mpc_msgs.Obstacles.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_mpc_msgs.Obstacles;
            obj.reload(strObj);
        end
    end
end
