classdef Output < robotics.ros.Message
    %Output MATLAB implementation of nautonomous_mpc_msgs/Output
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_mpc_msgs/Output' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '975fc919669306650ac32739939d0696' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        NautonomousMpcMsgsStageVariableClass = robotics.ros.msg.internal.MessageFactory.getClassForType('nautonomous_mpc_msgs/StageVariable') % Dispatch to MATLAB class for message type nautonomous_mpc_msgs/StageVariable
    end
    
    properties (Dependent)
        Exitflag
        Z
    end
    
    properties (Access = protected)
        Cache = struct('Z', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Exitflag', 'Z'} % List of non-constant message properties
        ROSPropertyList = {'exitflag', 'Z'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Output(msg)
            %Output Construct the message object Output
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function exitflag = get.Exitflag(obj)
            %get.Exitflag Get the value for property Exitflag
            exitflag = int32(obj.JavaMessage.getExitflag);
        end
        
        function set.Exitflag(obj, exitflag)
            %set.Exitflag Set the value for property Exitflag
            validateattributes(exitflag, {'numeric'}, {'nonempty', 'scalar'}, 'Output', 'Exitflag');
            
            obj.JavaMessage.setExitflag(exitflag);
        end
        
        function z = get.Z(obj)
            %get.Z Get the value for property Z
            if isempty(obj.Cache.Z)
                javaArray = obj.JavaMessage.getZ;
                array = obj.readJavaArray(javaArray, obj.NautonomousMpcMsgsStageVariableClass);
                obj.Cache.Z = feval(obj.NautonomousMpcMsgsStageVariableClass, array);
            end
            z = obj.Cache.Z;
        end
        
        function set.Z(obj, z)
            %set.Z Set the value for property Z
            if ~isvector(z) && isempty(z)
                % Allow empty [] input
                z = feval([obj.NautonomousMpcMsgsStageVariableClass '.empty'], 0, 1);
            end
            
            validateattributes(z, {obj.NautonomousMpcMsgsStageVariableClass}, {'vector'}, 'Output', 'Z');
            
            javaArray = obj.JavaMessage.getZ;
            array = obj.writeJavaArray(z, javaArray, obj.NautonomousMpcMsgsStageVariableClass);
            obj.JavaMessage.setZ(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Z)
                obj.Cache.Z = [];
                obj.Cache.Z = obj.Z;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Z = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Exitflag = obj.Exitflag;
            
            % Recursively copy compound properties
            cpObj.Z = copy(obj.Z);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Exitflag = strObj.Exitflag;
            ZCell = arrayfun(@(x) feval([obj.NautonomousMpcMsgsStageVariableClass '.loadobj'], x), strObj.Z, 'UniformOutput', false);
            obj.Z = vertcat(ZCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Exitflag = obj.Exitflag;
            strObj.Z = arrayfun(@(x) saveobj(x), obj.Z);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_mpc_msgs.Output.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_mpc_msgs.Output;
            obj.reload(strObj);
        end
    end
end
