classdef BoatCommand < robotics.ros.Message
    %BoatCommand MATLAB implementation of nautonomous_state_msgs/BoatCommand
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_state_msgs/BoatCommand' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ade378c6a9b0c8e4dc9ebc1fd3fc40be' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        UL
        UR
    end
    
    properties (Constant, Hidden)
        PropertyList = {'UL', 'UR'} % List of non-constant message properties
        ROSPropertyList = {'u_l', 'u_r'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = BoatCommand(msg)
            %BoatCommand Construct the message object BoatCommand
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function ul = get.UL(obj)
            %get.UL Get the value for property UL
            ul = double(obj.JavaMessage.getUL);
        end
        
        function set.UL(obj, ul)
            %set.UL Set the value for property UL
            validateattributes(ul, {'numeric'}, {'nonempty', 'scalar'}, 'BoatCommand', 'UL');
            
            obj.JavaMessage.setUL(ul);
        end
        
        function ur = get.UR(obj)
            %get.UR Get the value for property UR
            ur = double(obj.JavaMessage.getUR);
        end
        
        function set.UR(obj, ur)
            %set.UR Set the value for property UR
            validateattributes(ur, {'numeric'}, {'nonempty', 'scalar'}, 'BoatCommand', 'UR');
            
            obj.JavaMessage.setUR(ur);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.UL = obj.UL;
            cpObj.UR = obj.UR;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.UL = strObj.UL;
            obj.UR = strObj.UR;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.UL = obj.UL;
            strObj.UR = obj.UR;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_state_msgs.BoatCommand.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_state_msgs.BoatCommand;
            obj.reload(strObj);
        end
    end
end
