classdef Border < robotics.ros.Message
    %Border MATLAB implementation of nautonomous_state_msgs/Border
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_state_msgs/Border' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '3fb3f9dacc279b964c4c8341122c34df' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPointClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point') % Dispatch to MATLAB class for message type geometry_msgs/Point
    end
    
    properties (Dependent)
        Points
    end
    
    properties (Access = protected)
        Cache = struct('Points', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Points'} % List of non-constant message properties
        ROSPropertyList = {'points'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Border(msg)
            %Border Construct the message object Border
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function points = get.Points(obj)
            %get.Points Get the value for property Points
            if isempty(obj.Cache.Points)
                javaArray = obj.JavaMessage.getPoints;
                array = obj.readJavaArray(javaArray, obj.GeometryMsgsPointClass);
                obj.Cache.Points = feval(obj.GeometryMsgsPointClass, array);
            end
            points = obj.Cache.Points;
        end
        
        function set.Points(obj, points)
            %set.Points Set the value for property Points
            if ~isvector(points) && isempty(points)
                % Allow empty [] input
                points = feval([obj.GeometryMsgsPointClass '.empty'], 0, 1);
            end
            
            validateattributes(points, {obj.GeometryMsgsPointClass}, {'vector'}, 'Border', 'Points');
            
            javaArray = obj.JavaMessage.getPoints;
            array = obj.writeJavaArray(points, javaArray, obj.GeometryMsgsPointClass);
            obj.JavaMessage.setPoints(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Points)
                obj.Cache.Points = [];
                obj.Cache.Points = obj.Points;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Points = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Points = copy(obj.Points);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            PointsCell = arrayfun(@(x) feval([obj.GeometryMsgsPointClass '.loadobj'], x), strObj.Points, 'UniformOutput', false);
            obj.Points = vertcat(PointsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Points = arrayfun(@(x) saveobj(x), obj.Points);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_state_msgs.Border.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_state_msgs.Border;
            obj.reload(strObj);
        end
    end
end
