classdef Borders < robotics.ros.Message
    %Borders MATLAB implementation of nautonomous_state_msgs/Borders
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_state_msgs/Borders' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ac20490ce0a6dfccc4a49f3442beb7f8' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        NautonomousStateMsgsBorderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('nautonomous_state_msgs/Border') % Dispatch to MATLAB class for message type nautonomous_state_msgs/Border
    end
    
    properties (Dependent)
        Borders_
    end
    
    properties (Access = protected)
        Cache = struct('Borders_', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Borders_'} % List of non-constant message properties
        ROSPropertyList = {'borders'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Borders(msg)
            %Borders Construct the message object Borders
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function borders_ = get.Borders_(obj)
            %get.Borders_ Get the value for property Borders_
            if isempty(obj.Cache.Borders_)
                javaArray = obj.JavaMessage.getBorders;
                array = obj.readJavaArray(javaArray, obj.NautonomousStateMsgsBorderClass);
                obj.Cache.Borders_ = feval(obj.NautonomousStateMsgsBorderClass, array);
            end
            borders_ = obj.Cache.Borders_;
        end
        
        function set.Borders_(obj, borders_)
            %set.Borders_ Set the value for property Borders_
            if ~isvector(borders_) && isempty(borders_)
                % Allow empty [] input
                borders_ = feval([obj.NautonomousStateMsgsBorderClass '.empty'], 0, 1);
            end
            
            validateattributes(borders_, {obj.NautonomousStateMsgsBorderClass}, {'vector'}, 'Borders', 'Borders_');
            
            javaArray = obj.JavaMessage.getBorders;
            array = obj.writeJavaArray(borders_, javaArray, obj.NautonomousStateMsgsBorderClass);
            obj.JavaMessage.setBorders(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Borders_)
                obj.Cache.Borders_ = [];
                obj.Cache.Borders_ = obj.Borders_;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Borders_ = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Borders_ = copy(obj.Borders_);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            Borders_Cell = arrayfun(@(x) feval([obj.NautonomousStateMsgsBorderClass '.loadobj'], x), strObj.Borders_, 'UniformOutput', false);
            obj.Borders_ = vertcat(Borders_Cell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Borders_ = arrayfun(@(x) saveobj(x), obj.Borders_);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_state_msgs.Borders.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_state_msgs.Borders;
            obj.reload(strObj);
        end
    end
end
