/* This function was automatically generated by CasADi */#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) FORCESNLPsolver_model_50_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_FLOAT CASADI_PREFIX(sq)(FORCESNLPsolver_FLOAT x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_FLOAT CASADI_PREFIX(sign)(FORCESNLPsolver_FLOAT x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {42, 1, 0, 42, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {1, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {6, 8, 0, 0, 0, 6, 12, 12, 12, 12, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
int FORCESNLPsolver_model_50(const FORCESNLPsolver_FLOAT** arg, FORCESNLPsolver_FLOAT** res) {
     FORCESNLPsolver_FLOAT a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49;
         a0=arg[0] ? arg[0][2] : 0;
         a1=arg[1] ? arg[1][8] : 0;
  a1=(a0-a1);
         a2=sq(a1);
         a3=arg[0] ? arg[0][3] : 0;
         a4=arg[1] ? arg[1][9] : 0;
  a4=(a3-a4);
         a5=sq(a4);
  a2=(a2+a5);
  a5=arg[1] ? arg[1][10] : 0;
  a2=(a5*a2);
         a6=0.;
         a7=arg[0] ? arg[0][0] : 0;
         a8=(a6<=a7);
         a9=(a8?a7:0);
         a10=arg[1] ? arg[1][3] : 0;
  a7=(a7/a10);
         a11=(!a8);
  a7=(a11?a7:0);
  a9=(a9+a7);
  a7=sq(a9);
         a12=arg[0] ? arg[0][1] : 0;
  a6=(a6<=a12);
         a13=(a6?a12:0);
  a12=(a12/a10);
         a14=(!a6);
  a12=(a14?a12:0);
  a13=(a13+a12);
  a12=sq(a13);
  a7=(a7+a12);
  a12=arg[1] ? arg[1][11] : 0;
  a7=(a12*a7);
  a2=(a2+a7);
  if (res[0]!=0) res[0][0]=a2;
  a9=(a9+a9);
  a9=(a9*a12);
  a11=(a11*a9);
  a11=(a11/a10);
  a8=(a8*a9);
  a11=(a11+a8);
  if (res[1]!=0) res[1][0]=a11;
  a13=(a13+a13);
  a13=(a13*a12);
  a14=(a14*a13);
  a14=(a14/a10);
  a6=(a6*a13);
  a14=(a14+a6);
  if (res[1]!=0) res[1][1]=a14;
  a1=(a1+a1);
  a1=(a1*a5);
  if (res[1]!=0) res[1][2]=a1;
  a4=(a4+a4);
  a4=(a4*a5);
  if (res[1]!=0) res[1][3]=a4;
  a4=arg[1] ? arg[1][12] : 0;
  a5=(a0-a4);
  a1=arg[1] ? arg[1][36] : 0;
  a14=cos(a1);
  a5=(a5*a14);
  a6=arg[1] ? arg[1][18] : 0;
  a13=(a3-a6);
  a10=sin(a1);
  a13=(a13*a10);
  a5=(a5+a13);
  a13=arg[1] ? arg[1][24] : 0;
  a5=(a5/a13);
  a12=sq(a5);
  a6=(a3-a6);
  a11=cos(a1);
  a6=(a6*a11);
  a4=(a0-a4);
  a1=sin(a1);
  a4=(a4*a1);
  a6=(a6-a4);
  a4=arg[1] ? arg[1][30] : 0;
  a6=(a6/a4);
  a8=sq(a6);
  a12=(a12+a8);
  if (res[2]!=0) res[2][0]=a12;
  a12=arg[1] ? arg[1][13] : 0;
  a8=(a0-a12);
  a9=arg[1] ? arg[1][37] : 0;
  a2=cos(a9);
  a8=(a8*a2);
  a7=arg[1] ? arg[1][19] : 0;
         a15=(a3-a7);
         a16=sin(a9);
  a15=(a15*a16);
  a8=(a8+a15);
  a15=arg[1] ? arg[1][25] : 0;
  a8=(a8/a15);
         a17=sq(a8);
  a7=(a3-a7);
         a18=cos(a9);
  a7=(a7*a18);
  a12=(a0-a12);
  a9=sin(a9);
  a12=(a12*a9);
  a7=(a7-a12);
  a12=arg[1] ? arg[1][31] : 0;
  a7=(a7/a12);
         a19=sq(a7);
  a17=(a17+a19);
  if (res[2]!=0) res[2][1]=a17;
  a17=arg[1] ? arg[1][14] : 0;
  a19=(a0-a17);
         a20=arg[1] ? arg[1][38] : 0;
         a21=cos(a20);
  a19=(a19*a21);
         a22=arg[1] ? arg[1][20] : 0;
         a23=(a3-a22);
         a24=sin(a20);
  a23=(a23*a24);
  a19=(a19+a23);
  a23=arg[1] ? arg[1][26] : 0;
  a19=(a19/a23);
         a25=sq(a19);
  a22=(a3-a22);
         a26=cos(a20);
  a22=(a22*a26);
  a17=(a0-a17);
  a20=sin(a20);
  a17=(a17*a20);
  a22=(a22-a17);
  a17=arg[1] ? arg[1][32] : 0;
  a22=(a22/a17);
         a27=sq(a22);
  a25=(a25+a27);
  if (res[2]!=0) res[2][2]=a25;
  a25=arg[1] ? arg[1][15] : 0;
  a27=(a0-a25);
         a28=arg[1] ? arg[1][39] : 0;
         a29=cos(a28);
  a27=(a27*a29);
         a30=arg[1] ? arg[1][21] : 0;
         a31=(a3-a30);
         a32=sin(a28);
  a31=(a31*a32);
  a27=(a27+a31);
  a31=arg[1] ? arg[1][27] : 0;
  a27=(a27/a31);
         a33=sq(a27);
  a30=(a3-a30);
         a34=cos(a28);
  a30=(a30*a34);
  a25=(a0-a25);
  a28=sin(a28);
  a25=(a25*a28);
  a30=(a30-a25);
  a25=arg[1] ? arg[1][33] : 0;
  a30=(a30/a25);
         a35=sq(a30);
  a33=(a33+a35);
  if (res[2]!=0) res[2][3]=a33;
  a33=arg[1] ? arg[1][16] : 0;
  a35=(a0-a33);
         a36=arg[1] ? arg[1][40] : 0;
         a37=cos(a36);
  a35=(a35*a37);
         a38=arg[1] ? arg[1][22] : 0;
         a39=(a3-a38);
         a40=sin(a36);
  a39=(a39*a40);
  a35=(a35+a39);
  a39=arg[1] ? arg[1][28] : 0;
  a35=(a35/a39);
         a41=sq(a35);
  a38=(a3-a38);
         a42=cos(a36);
  a38=(a38*a42);
  a33=(a0-a33);
  a36=sin(a36);
  a33=(a33*a36);
  a38=(a38-a33);
  a33=arg[1] ? arg[1][34] : 0;
  a38=(a38/a33);
         a43=sq(a38);
  a41=(a41+a43);
  if (res[2]!=0) res[2][4]=a41;
  a41=arg[1] ? arg[1][17] : 0;
  a43=(a0-a41);
         a44=arg[1] ? arg[1][41] : 0;
         a45=cos(a44);
  a43=(a43*a45);
         a46=arg[1] ? arg[1][23] : 0;
         a47=(a3-a46);
         a48=sin(a44);
  a47=(a47*a48);
  a43=(a43+a47);
  a47=arg[1] ? arg[1][29] : 0;
  a43=(a43/a47);
         a49=sq(a43);
  a3=(a3-a46);
  a46=cos(a44);
  a3=(a3*a46);
  a0=(a0-a41);
  a44=sin(a44);
  a0=(a0*a44);
  a3=(a3-a0);
  a0=arg[1] ? arg[1][35] : 0;
  a3=(a3/a0);
  a41=sq(a3);
  a49=(a49+a41);
  if (res[2]!=0) res[2][5]=a49;
  a5=(a5+a5);
  a14=(a14/a13);
  a14=(a5*a14);
  a6=(a6+a6);
  a1=(a1/a4);
  a1=(a6*a1);
  a14=(a14-a1);
  if (res[3]!=0) res[3][0]=a14;
  a8=(a8+a8);
  a2=(a2/a15);
  a2=(a8*a2);
  a7=(a7+a7);
  a9=(a9/a12);
  a9=(a7*a9);
  a2=(a2-a9);
  if (res[3]!=0) res[3][1]=a2;
  a19=(a19+a19);
  a21=(a21/a23);
  a21=(a19*a21);
  a22=(a22+a22);
  a20=(a20/a17);
  a20=(a22*a20);
  a21=(a21-a20);
  if (res[3]!=0) res[3][2]=a21;
  a27=(a27+a27);
  a29=(a29/a31);
  a29=(a27*a29);
  a30=(a30+a30);
  a28=(a28/a25);
  a28=(a30*a28);
  a29=(a29-a28);
  if (res[3]!=0) res[3][3]=a29;
  a35=(a35+a35);
  a37=(a37/a39);
  a37=(a35*a37);
  a38=(a38+a38);
  a36=(a36/a33);
  a36=(a38*a36);
  a37=(a37-a36);
  if (res[3]!=0) res[3][4]=a37;
  a43=(a43+a43);
  a45=(a45/a47);
  a45=(a43*a45);
  a3=(a3+a3);
  a44=(a44/a0);
  a44=(a3*a44);
  a45=(a45-a44);
  if (res[3]!=0) res[3][5]=a45;
  a10=(a10/a13);
  a5=(a5*a10);
  a11=(a11/a4);
  a6=(a6*a11);
  a5=(a5+a6);
  if (res[3]!=0) res[3][6]=a5;
  a16=(a16/a15);
  a8=(a8*a16);
  a18=(a18/a12);
  a7=(a7*a18);
  a8=(a8+a7);
  if (res[3]!=0) res[3][7]=a8;
  a24=(a24/a23);
  a19=(a19*a24);
  a26=(a26/a17);
  a22=(a22*a26);
  a19=(a19+a22);
  if (res[3]!=0) res[3][8]=a19;
  a32=(a32/a31);
  a27=(a27*a32);
  a34=(a34/a25);
  a30=(a30*a34);
  a27=(a27+a30);
  if (res[3]!=0) res[3][9]=a27;
  a40=(a40/a39);
  a35=(a35*a40);
  a42=(a42/a33);
  a38=(a38*a42);
  a35=(a35+a38);
  if (res[3]!=0) res[3][10]=a35;
  a48=(a48/a47);
  a43=(a43*a48);
  a46=(a46/a0);
  a3=(a3*a46);
  a43=(a43+a3);
  if (res[3]!=0) res[3][11]=a43;
  return 0;
}

int FORCESNLPsolver_model_50_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  *f_type = 1;
  *n_in = 2;
  *n_out = 4;
  *sz_arg = 2;
  *sz_res = 4;
  return 0;
}

int FORCESNLPsolver_model_50_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row) {
  const int* s;
  switch (i) {
    case 0:
      s = s0; break;
    case 1:
      s = s1; break;
    case 2:
      s = s2; break;
    case 3:
      s = s3; break;
    case 4:
      s = s4; break;
    case 5:
      s = s5; break;
    default:
      return 1;
  }

  *nrow = s[0];
  *ncol = s[1];
  *colind = s + 2;
  *row = s + 2 + (*ncol + 1);
  return 0;
}

int FORCESNLPsolver_model_50_work(int *sz_iw, int *sz_w) {
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 50;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
