classdef RouteRequest < robotics.ros.Message
    %RouteRequest MATLAB implementation of nautonomous_routing_msgs/RouteRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'nautonomous_routing_msgs/RouteRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f1dde56120b7c8f7b408b7b060727124' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPose2DClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Pose2D') % Dispatch to MATLAB class for message type geometry_msgs/Pose2D
    end
    
    properties (Dependent)
        Start
        Destination
    end
    
    properties (Access = protected)
        Cache = struct('Start', [], 'Destination', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Destination', 'Start'} % List of non-constant message properties
        ROSPropertyList = {'destination', 'start'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = RouteRequest(msg)
            %RouteRequest Construct the message object RouteRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function start = get.Start(obj)
            %get.Start Get the value for property Start
            if isempty(obj.Cache.Start)
                obj.Cache.Start = feval(obj.GeometryMsgsPose2DClass, obj.JavaMessage.getStart);
            end
            start = obj.Cache.Start;
        end
        
        function set.Start(obj, start)
            %set.Start Set the value for property Start
            validateattributes(start, {obj.GeometryMsgsPose2DClass}, {'nonempty', 'scalar'}, 'RouteRequest', 'Start');
            
            obj.JavaMessage.setStart(start.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Start)
                obj.Cache.Start.setJavaObject(start.getJavaObject);
            end
        end
        
        function destination = get.Destination(obj)
            %get.Destination Get the value for property Destination
            if isempty(obj.Cache.Destination)
                obj.Cache.Destination = feval(obj.GeometryMsgsPose2DClass, obj.JavaMessage.getDestination);
            end
            destination = obj.Cache.Destination;
        end
        
        function set.Destination(obj, destination)
            %set.Destination Set the value for property Destination
            validateattributes(destination, {obj.GeometryMsgsPose2DClass}, {'nonempty', 'scalar'}, 'RouteRequest', 'Destination');
            
            obj.JavaMessage.setDestination(destination.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Destination)
                obj.Cache.Destination.setJavaObject(destination.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Start = [];
            obj.Cache.Destination = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Start = copy(obj.Start);
            cpObj.Destination = copy(obj.Destination);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Start = feval([obj.GeometryMsgsPose2DClass '.loadobj'], strObj.Start);
            obj.Destination = feval([obj.GeometryMsgsPose2DClass '.loadobj'], strObj.Destination);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Start = saveobj(obj.Start);
            strObj.Destination = saveobj(obj.Destination);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.nautonomous_routing_msgs.RouteRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.nautonomous_routing_msgs.RouteRequest;
            obj.reload(strObj);
        end
    end
end
